import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import gradientimage from "../../public/gradient.webp";
import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react";
const myFont = localFont({
  variable: "--font-cal",
  src: "../../public/CalSans-Regular.woff2",
});
const geistmono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});
const poppinsSans = Poppins({
  subsets: ["latin"], // Or other desired subsets
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Or specific weights
  variable: "--font-poppins", // CSS variable name
  display: "swap", // Or 'block', 'fallback'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/svg+xml" href="./m-bg.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Mann Patel's personal website. A place to showcase my projects and skills."
        />
        <meta
          name="keywords"
          content="Mann Patel, Mann, Patel, Mann Patel's website, Mann Patel's personal website, Mann Patel's portfolio, Mann Patel's projects, Mann Patel's skills"
        />
        <meta name="author" content="Mann Patel" />
        <meta name="og:title" content="Mann Patel's portfolio website" />
        <meta name="og:type" content="website" />
        <meta name="og:url" content="https://mspatel18.vercel.app" />
        <meta name="og:image" content="./m-bg.png" />
        <meta name="og:description" content="Software Developer, India" />
        <meta name="og:site_name" content="Mann Patel" />

        <title>Mann Patel</title>
      </head>
      <body
        className={`${poppinsSans.className} ${geistmono.variable} ${myFont.variable}  `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container max-w-4xl mx-auto min-h-screen flex flex-col px-4 pt-5">
            <Image
              src={gradientimage}
              alt=""
              className="absolute left-0 sm:left-1/2 top-0 -z-10 -translate-x-1/2 lg:scale-100 object-cover "
            />
            <Navbar />

            <section className="md:mt-8 lg:mt-10 pt-8 pb-8">{children}</section>
            <footer className="border-t p-2 text-sm italic">
              Made by{" "}
              <a href="https://github.com/mspatel18" className="font-bold">
                @mspatel18
              </a>
              {" </>"}
            </footer>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
